import { Fragrance } from './fragrance.model';

export const INITIAL_FRAGRANCES: Fragrance[] = [
  { name: 'Creed Aventus', status: 'enjoy' },
  { name: 'Chanel Bleu de Chanel EDP', status: null },
  { name: 'Giorgio Armani Acqua Di Gio Profumo', status: 'enjoy' },
  { name: 'Creed Aventus Absolu', status: 'enjoy' },
  { name: "Kilian Angels' Share", status: 'enjoy' },
  { name: 'Clive Christian Jump Up And Kiss Me Hedonistic', status: 'enjoy' },
  { name: 'Parfums de Marly Layton', status: null },
  { name: 'Chanel Bleu de Chanel Parfum (2018)', status: null },
  { name: 'Parfums de Marly Oajan', status: 'enjoy' },
  { name: 'Boadicea The Victorious Blue Sapphire', status: 'enjoy' },
  { name: 'Clive Christian Blonde Amber', status: 'enjoy' },
  { name: 'Hugo Boss Bottled Absolu', status: null },
  { name: 'Louis Vuitton Imagination', status: 'enjoy' },
  { name: 'Kilian Smoking Hot', status: 'enjoy' },
  { name: 'Xerjoff Naxos', status: 'enjoy' },
  { name: 'Amouage Reflection Man', status: null },
  { name: 'Clive Christian Rock Rose', status: null },
  { name: "Yves Saint Laurent L'Homme", status: null },
  { name: 'Memo African Leather', status: null },
  { name: 'Nishane Hacivat', status: null },
  { name: 'Christian Dior Sauvage Elixir', status: null },
  { name: 'Giorgio Armani Emporio Stronger With You Intensely', status: 'enjoy' },
  { name: 'Giorgio Armani Emporio Stronger With You Absolutely', status: 'enjoy' },
  { name: 'Azzaro The Most Wanted EDP', status: null },
  { name: 'Initio Parfums Prives Side Effect', status: 'enjoy' },
  { name: 'Parfums de Marly Althair', status: null },
  { name: 'Bottega Veneta Pour Homme', status: 'enjoy' },
  { name: 'Giorgio Armani Emporio Stronger With You', status: null },
  { name: 'Tom Ford Noir Extreme', status: null },
  { name: 'Tom Ford Tobacco Vanille', status: null },
  { name: 'Bvlgari Tygar', status: null },
  { name: 'Amouage Reflection 45', status: null },
  { name: 'Roja Dove Enigma Pour Homme Parfum Cologne', status: 'enjoy' },
  { name: 'Viktor & Rolf Spicebomb', status: null },
  { name: 'Amouage Outlands', status: 'enjoy' },
  { name: 'Jean Paul Gaultier Le Male Le Parfum', status: null },
  { name: 'Xerjoff Tony Iommi Monkey Special', status: null },
  { name: 'Giorgio Armani Emporio Armani - Stronger With You Sandalwood', status: null },
  { name: 'Ex Nihilo The Hedonist Extrait de Parfum', status: null },
  { name: 'Christian Dior Homme Intense', status: null },
  { name: 'Sospiro Vibrato', status: null },
  { name: 'Thameen Carved Oud', status: null },
  { name: 'Roja Dove Burlington 1819', status: null },
  { name: "Chanel Bleu de Chanel L'Exclusif", status: null },
  { name: 'Parfums de Marly Herod', status: null },
  { name: 'Mont Blanc Explorer', status: null },
  { name: 'Chanel Allure Homme Edition Blanche Eau De Parfum', status: 'enjoy' },
  { name: 'Parfums de Marly Sedley', status: 'enjoy' },
  { name: 'Maison Francis Kurkdjian Grand Soir', status: null },
  { name: 'Christian Dior Homme 2020', status: null },
  { name: 'Parfums de Marly Greenley', status: null },
  { name: 'Xerjoff Torino 21', status: null },
  { name: 'Viktor & Rolf Spicebomb Extreme', status: null },
  { name: 'Initio Parfums Prives Rehab', status: null },
  { name: 'Maison Francis Kurkdjian Amyris Homme Extrait de Parfum', status: null },
  { name: 'Creed Royal Oud', status: null },
  { name: 'Orto Parisi Terroni', status: null },
  { name: 'Lattafa Khamrah', status: null },
  { name: 'Jean Paul Gaultier Le Male Elixir Absolu', status: null },
  { name: 'Giorgio Armani Acqua Di Gio Profondo', status: null },
  { name: "Prada L'Homme Intense", status: null },
  { name: 'Yves Saint Laurent Myslf', status: 'enjoy' },
  { name: 'Versace Pour Homme Dylan Blue', status: null },
  { name: 'Yves Saint Laurent Myslf Le Parfum', status: null },
  { name: 'Jean Paul Gaultier Ultra Male', status: 'enjoy' },
  { name: 'Kilian Apple Brandy On The Rocks', status: 'enjoy' },
  { name: 'Kilian Vodka On The Rocks', status: null },
  { name: 'Maison Francis Kurkdjian Gentle Fluidity Silver', status: null },
  { name: 'Chanel Allure Homme Sport Eau Extreme', status: null },
  { name: "Louis Vuitton L'Immensite", status: null },
  { name: 'Tom Ford Oud Wood', status: null },
  { name: 'Clive Christian Matsukita', status: null },
  { name: 'Maison Francis Kurkdjian Masculin Pluriel', status: null },
  { name: 'Parfums de Marly Pegasus Exclusif', status: null },
  { name: 'Chanel Allure Homme Sport', status: null },
  { name: 'Jean Paul Gaultier Le Male Elixir', status: null },
  { name: 'Parfums de Marly Haltane', status: null },
  { name: 'Roja Dove Parfum De La Nuit No 3', status: null },
  { name: 'Initio Parfums Prives Oud For Greatness', status: null },
  { name: 'Givenchy Gentleman Eau De Parfum Reserve Privee', status: null },
  { name: 'Chanel Bleu de Chanel EDT', status: null },
  { name: 'BDK Parfums Gris Charnel Extrait', status: null },
  { name: 'Yves Saint Laurent Y Eau De Parfum', status: null },
  { name: 'Xerjoff 40 Knots', status: null },
  { name: "Terre d'Hermès", status: null },
  { name: "Yves Saint Laurent La Nuit De L'Homme Bleu Electrique", status: null },
  { name: 'Initio Parfums Prives Paragon', status: null },
  { name: "Guerlain L'Homme Ideal Eau de Parfum", status: null },
  { name: "Yves Saint Laurent L'Homme", status: null },
  { name: 'Byredo Gypsy Water', status: 'enjoy' },
  { name: "Yves Saint Laurent Myslf L'Absolu", status: 'enjoy' },
  { name: 'Giorgio Armani Armani Code 2024', status: null },
  { name: 'Hermès H24 EDP', status: null },
  { name: 'Maison Francis Kurkdjian Baccarat Rouge 540', status: null },
  { name: 'Marc-Antoine Barrois Ganymede', status: null },
  { name: 'Roja Dove Elysium Pour Homme Parfum Cologne', status: null },
  { name: 'Maison Crivelli Oud Maracujá', status: null },
  { name: 'Tom Ford Ombré Leather', status: null },
  { name: 'Mancera Cedrat Boise', status: null },
  { name: "Hermès Terre d'Hermès Eau Intense Vetiver", status: null },
  { name: 'Chanel Egoïste Man', status: null },
  { name: 'Tom Ford Grey Vetiver', status: null },
  { name: 'Christian Dior Homme Sport 2021', status: null },
  { name: "Guerlain L'Instant de Guerlain pour Homme EDP", status: null },
  { name: 'Puredistance Black No. 05', status: null },
  { name: 'Gucci Intense Oud', status: null },
  { name: 'Amouage Jubilation XXV For Men', status: null },
  { name: 'Louis Vuitton Ombre Nomade', status: 'dislike' },
  { name: 'Tom Ford Tuscan Leather', status: null },
  { name: 'Hermès Vetiver Tonka', status: null },
  { name: 'Xerjoff Alexandria II', status: null },
  { name: 'Parfums de Marly Percival', status: 'dislike' },
  { name: 'Parfums de Marly Carlisle', status: 'dislike' },
  { name: 'Christian Dior Sauvage Parfum', status: null },
  { name: 'Christian Dior Fahrenheit Man EDT', status: null },
  { name: 'Swiss Arabian Incense 01', status: 'dislike' },
  { name: 'Nishane Ani', status: null },
  { name: 'Hugo Boss Bottled Man EDT', status: null },
  { name: 'Dolce & Gabbana The One for Men EDP', status: null },
  { name: 'Kilian Straight To Heaven White Cristal', status: null },
  { name: 'Le Labo Santal 33', status: 'dislike' },
  { name: 'Chanel Egoïste Platinum', status: 'dislike' },
  { name: 'Clinique Happy for Men EDT', status: null },
  { name: 'Baldessarini Ambré Man EDT', status: null },
  { name: 'Jacques Bogart Bogart Man EDT', status: null },
  { name: 'Gucci Pour Homme 2016 EDT', status: null },
  { name: 'Nasomatto Black Afgano', status: 'dislike' },
  { name: 'Chanel Sycomore', status: 'dislike' },
  { name: "Lalique Encre Noire A L'Extreme", status: 'dislike' },
];
